Explicitly fail the Done workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,6 +31,13 @@ jobs:
       - bare-metal
       - containerized
       - smoke-tests
+    if: '!cancelled()'
     steps:
       - name: Done
+        if: success()
         run: echo "Done!"
+      - name: Done
+        if: failure()
+        run: |-
+          echo "Failed!"
+          exit 1
